# Name of the GitHub Actions workflow
name: deploy

# Defines when the workflow will run
on:
  schedule:
    - cron: "0 10 * * 0" # Scheduled to run every week on Sunday at 10 AM

  # Allows manual triggering of the workflow from the GitHub Actions tab
  workflow_dispatch:
    
permissions:
  contents: write    

# Specifies the jobs to be executed in this workflow
jobs:
  # Defines a job named "build" that will run on the latest version of Ubuntu
  build:
    runs-on: ubuntu-latest

    # Defines a sequence of steps to be executed as part of the job
    steps:
      # Step 1: Checkout the main repository under $GITHUB_WORKSPACE
      - name: checkout our files
        uses: actions/checkout@v4
        with:
          ref: html

      # Step 2: Set up Node.js version 20.0
      - name: Use Node.js 20.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Run commands in the Node.js environment and executing 'index.js'
      - name: deploy app
        run: |
          ls -l
          find scheme syllabus timetable -type f -name '*.html' | sed 's|^scheme/|https://www.rgpv-syllabus-timetable.in/scheme/|; s|^syllabus/|https://www.rgpv-syllabus-timetable.in/syllabus/|; s|^timetable/|https://www.rgpv-syllabus-timetable.in/timetable/|' > listofurls.txt
          find scheme syllabus timetable -type f -name '*.html' -exec sed -i 's/<\/head>/<link rel="sitemap" type="application\/xml" title="Sitemap" href="\/sitemap.xml"><meta name="viewport" content="width=device-width, initial-scale=1" \/><\/head>/g' {} +
          find scheme syllabus timetable -type f -name '*.html' -exec sed -i 's|<body>|<body><div style="display:flex;justify-content:flex-end;"><a href="#" target="_blank" download="" id="pdf-download-link"><button type="button" style="cursor:pointer;-webkit-appearance:button;color:#fff;background-color:#007bff;border-color:#007bff;display:inline-block;font-weight:400;text-align:center;white-space:nowrap;vertical-align:middle;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;border:1px solid transparent;padding:0.375rem 0.75rem;font-size:1rem;line-height:1.5;border-radius:0.25rem;transition:color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;text-transform:none;overflow:visible;margin:0;font-family:inherit;" download>Download PDF</button></a></div><script>const a=(window.location.pathname).split("/");const filename="" + a[a.length-1] + ".pdf";document.getElementById("pdf-download-link").href=filename;</script>|g' {} +
          find scheme syllabus timetable -type f -name '*.html' -exec sed -i 's|<title>|<title>rgpv syllabus - rgpv timetable |g' {} +
          npm install --save sitemap
          cd ./node_modules/.bin/
          npx sitemap < ../../listofurls.txt>websiteurls.txt
          mv websiteurls.txt ../../sitemap.xml
          cd ../../
          mkdir deploy
          mv scheme syllabus timetable deploy/
          mv sitemap.xml deploy/sitemap.xml
          mv index.html deploy/index.html
          mv scheme.json deploy/scheme.json
          mv syllabus.json deploy/syllabus.json
          mv timetable.json deploy/timetable.json
          ls -a

      # Step 4: Publishing files on files branch
      - name: Deploying on github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: deploy # The branch should deploy to.
          folder: deploy # The folder to deploy.
